export const queryKeys = {
    CURRENT_USER: "CurrentUser",
    CATEGORIES: "Categories",
    CATEGORY_ITEMS: "CategoryItems",
    PRODUCT: "Product",
    PRODUCTS: "Products",
    ON_DISCOUNT_PRODUCTS: "DiscountProducts",
    CART_ITEMS: "CartItems",
    SHIPPING_METHODS: "ShippingMethods",
    ORDER_INFORMATION: "OrderInformation",
    SELECTED_SHIPPING_METHODS: "SelectedShippingMethods",
    STRIPE_CONFIG: "StripeConfig",
    PAYMENT_INTENT: "PaymentIntent",
    USER_ADDRESS: "UserAddress",
    WISHLIST: "Wishlist",
};
